"""Strategy and portfolio scaffold generator.

Generates production-level strategy files and portfolio folders with
comprehensive event handling, order management, and risk integration.
"""
from __future__ import annotations

import logging
import re
from pathlib import Path

logger = logging.getLogger(__name__)

# ===========================================================================
# BAR_SCAFFOLD — Complete bar-based strategy template
# ===========================================================================

BAR_SCAFFOLD = '''"""
{name} — Bar-based trading strategy.

Generated by TinoHelm scaffold generator.
Production-level template with full event handling, order management,
position lifecycle, and risk integration.

Architecture notes (READ BEFORE EDITING):
- NautilusTrader uses HEDGING OMS mode: each entry creates an independent
  position with its own stop-loss and take-profit orders.
- Config fields instrument_id, bar_type, order_id_tag, manage_stop are
  injected by the portfolio loader — NEVER hardcode them.
- Do NOT access self.clock, self.log, self.cache, or self.portfolio in
  __init__ — they are not initialized until on_start().
- All data subscriptions (subscribe_bars, subscribe_quote_ticks, etc.)
  MUST happen in on_start(). Callbacks will NEVER fire without them.
- Always use instrument.make_price() / instrument.make_qty() when creating
  order parameters — wrong precision causes OrderDenied.
- Quantity is UNSIGNED — never pass negative values to Quantity.
- Money objects stringify with currency suffix ("114.60 USDT"). Use
  .as_double() for float values.
- TriggerType.LAST_TRADE does NOT exist — use TriggerType.LAST_PRICE.
"""
from __future__ import annotations

from collections import deque
from decimal import Decimal
from typing import Any

from nautilus_trader.config import StrategyConfig
from nautilus_trader.model import InstrumentId
from nautilus_trader.model.data import Bar, BarType
from nautilus_trader.model.enums import OrderSide, TimeInForce, TriggerType
from nautilus_trader.model.events import (
    OrderDenied,
    OrderFilled,
    OrderRejected,
    PositionChanged,
    PositionClosed,
    PositionOpened,
)
from nautilus_trader.model.identifiers import PositionId
from nautilus_trader.model.objects import Price, Quantity
from nautilus_trader.trading.strategy import Strategy

from tinohelm.strategy.state import stateful
from tinohelm.strategy.utils import is_paused, setup_pause_support


# ---------------------------------------------------------------------------
# Symbol Profiles (optional per-symbol parameter overrides)
# ---------------------------------------------------------------------------
# Keys use Jesse format: "BTC-USDT", "ETH-USDT", etc.
# The loader validates symbols against this dict and warns on unrecognized ones.
# Delete this entire section if your strategy uses the same params for all symbols.
SYMBOL_PROFILES: dict[str, dict] = {{
    "BTC-USDT": {{
        "trade_size": Decimal("0.001"),
        "stop_atr_mult": 1.5,
        "tp_atr_mult": 2.5,
    }},
    "ETH-USDT": {{
        "trade_size": Decimal("0.01"),
        "stop_atr_mult": 1.8,
        "tp_atr_mult": 3.0,
    }},
}}

DEFAULT_PROFILE: dict = {{
    "trade_size": Decimal("0.01"),
    "stop_atr_mult": 1.5,
    "tp_atr_mult": 2.5,
}}


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

class {class_name}Config(StrategyConfig):
    """Configuration for {class_name}.

    Fields injected by the loader (do NOT set in portfolio.yaml params):
        instrument_id, bar_type, order_id_tag, manage_stop,
        manage_gtd_expiry, oms_type, external_order_claims

    Add your strategy-specific parameters below.
    """
    instrument_id: InstrumentId
    bar_type: BarType
    trade_size: Decimal = Decimal("0.01")
    # --- Add your custom params here ---
    # lookback_window: int = 100
    # stop_atr_mult: float = 1.5
    # tp_atr_mult: float = 2.5
    # max_positions: int = 3


# ---------------------------------------------------------------------------
# Strategy
# ---------------------------------------------------------------------------

# @stateful auto-generates on_save / on_load / on_reset for the listed fields.
# For complex types (deque, dict with tuple keys), supply custom encoders:
#   @stateful("bar_count", "price_window",
#             encoders={{"price_window": (list, lambda x: deque(x, maxlen=100))}})
@stateful("bar_count", "last_signal")
class {class_name}(Strategy):
    """{name} trading strategy.

    HEDGING mode: each submit_order() creates an independent position.
    Link exit orders to a position via: submit_order(order, position_id=pid)

    Event flow:
        on_start → [on_bar loops → order/position events] → on_stop

    Order lifecycle:
        submit_order()
          → OrderDenied (NT RiskEngine blocked it — never sent to exchange)
          OR → OrderRejected (exchange rejected it — margin, limits, etc.)
          OR → OrderFilled → PositionOpened / PositionChanged / PositionClosed

    Available order types:
        self.order_factory.market(...)           # Market order
        self.order_factory.limit(...)            # Limit order
        self.order_factory.stop_market(...)      # Stop-loss trigger
        self.order_factory.stop_limit(...)       # Stop-limit
        self.order_factory.market_if_touched(...)
        self.order_factory.limit_if_touched(...)
        self.order_factory.trailing_stop_market(...)

    Time-in-force: GTC (default), IOC, FOK, GTD, DAY

    Useful cache/portfolio APIs:
        self.cache.instrument(instrument_id)
        self.cache.positions_open(instrument_id=id)
        self.cache.orders_open(instrument_id=id)
        self.cache.bar(bar_type, index=0)        # Most recent bar
        self.cache.bar_count(bar_type)
        self.portfolio.unrealized_pnl(instrument_id)
        self.portfolio.net_exposures(venue)       # Prefer over manual loop
        self.portfolio.account(venue).balance_free(currency)
    """

    def __init__(self, config: {class_name}Config) -> None:
        super().__init__(config)
        # Config fields
        self.instrument_id = config.instrument_id
        self.bar_type = config.bar_type
        self.trade_size = config.trade_size

        # State persisted by @stateful across live restarts
        self.bar_count: int = 0
        self.last_signal: str | None = None

        # Position tracking: {{position_id_str: {{"stop_oid": ..., "tp_oid": ..., ...}}}}
        self._open_positions: dict[str, dict] = {{}}

        # Risk guard state: "normal" | "reduce_only" | "halt_new" | "flatten_all"
        self._risk_state: str = "normal"

        # WARNING: Do NOT access self.log, self.clock, self.cache, self.portfolio
        # here — they are not yet initialized until on_start().

    # ===================================================================
    # LIFECYCLE
    # ===================================================================

    def on_start(self) -> None:
        """Called when the strategy starts. Subscribe to data here.

        CRITICAL: All subscribe_*() calls must happen here.
        on_bar() will NEVER fire without subscribe_bars().
        """
        # Fetch instrument — needed for precision-safe order creation
        self.instrument = self.cache.instrument(self.instrument_id)
        if self.instrument is None:
            self.log.error(f"Instrument not found: {{self.instrument_id}}")
            self.stop()
            return

        # Cache venue and currency — resolve once, reuse everywhere.
        # Do NOT create Venue/Currency objects on every bar tick.
        self._venue = self.instrument.venue
        self._currency = self.instrument.quote_currency

        # Enable L1 lifecycle pause support (LifecycleController integration)
        setup_pause_support(self)

        # Subscribe to bar data — REQUIRED for on_bar() to fire
        self.subscribe_bars(self.bar_type)

        # Subscribe to RiskGuard breach signals via msgbus
        self.msgbus.subscribe("risk.guard.state", self._on_risk_guard_state)

        # Optional: subscribe to additional data
        # self.subscribe_quote_ticks(self.instrument_id)   # → on_quote_tick()
        # self.subscribe_trade_ticks(self.instrument_id)   # → on_trade_tick()
        # self.subscribe_order_book(self.instrument_id)    # → on_order_book()
        # self.subscribe_signal("my_signal")               # → on_signal()

        # Optional: register indicators for automatic bar updates
        # self.register_indicator_for_bars(self.bar_type, my_indicator)

        # Optional: set a recurring timer → on_event(TimeEvent)
        # import pandas as pd
        # self.clock.set_timer("rebalance", interval=pd.Timedelta(hours=1))

        self.log.info(f"Strategy started on {{self.instrument_id}}")

    def on_stop(self) -> None:
        """Called when the strategy stops.

        If manage_stop=True (set by loader), market_exit() runs automatically
        BEFORE on_stop(), cancelling all orders and closing all positions.
        The calls below are a safety net.
        """
        self.cancel_all_orders(self.instrument_id)
        self.close_all_positions(self.instrument_id)
        self.log.info("Strategy stopped")

    # ===================================================================
    # DATA EVENTS
    # ===================================================================

    def on_bar(self, bar: Bar) -> None:
        """Called on each new bar. Core trading logic goes here.

        Bar fields: bar.open, bar.high, bar.low, bar.close, bar.volume
        Bar timing: bar.ts_init = bar close time (prevents look-ahead bias)
        """
        # L1 soft pause — skip all new-order logic when paused by LifecycleController
        if is_paused(self):
            return

        # Risk guard gate
        if self._risk_state == "halt_new":
            return  # No new orders allowed
        # "reduce_only": only position-reducing orders allowed (see _submit_entry)

        self.bar_count += 1

        # --- YOUR TRADING LOGIC HERE ---
        #
        # Example pattern:
        #
        # # Compute indicators
        # close = float(bar.close)
        # # ... your signal logic ...
        #
        # # Entry signals
        # if should_go_long:
        #     self._submit_entry(OrderSide.BUY)
        # elif should_go_short:
        #     self._submit_entry(OrderSide.SELL)
        #
        # # Position management (optional — can also use on_position_changed)
        # for pid_str, tracking in list(self._open_positions.items()):
        #     # e.g., trailing stop adjustment
        #     pass

    # ===================================================================
    # ORDER EVENTS
    # ===================================================================

    def on_order_rejected(self, event: OrderRejected) -> None:
        """Exchange rejected our order (sent but failed).

        Common causes: insufficient margin, position limit reached,
        price outside allowed range, lot size violation.
        MUST clean up tracking state for the failed order.
        """
        self.log.warning(
            f"Order REJECTED by exchange: {{event.client_order_id}} — {{event.reason}}"
        )
        self._cleanup_order_tracking(event.client_order_id)

    def on_order_denied(self, event: OrderDenied) -> None:
        """NT RiskEngine denied our order BEFORE sending to exchange.

        Common causes:
        - Price/quantity precision mismatch → use instrument.make_price/make_qty
        - Exceeds max notional or min quantity
        - reduce_only order on wrong side
        This is separate from on_order_rejected (exchange-level).
        """
        self.log.warning(
            f"Order DENIED by RiskEngine: {{event.client_order_id}} — {{event.reason}}"
        )
        self._cleanup_order_tracking(event.client_order_id)

    def on_order_filled(self, event: OrderFilled) -> None:
        """Called on every fill (including partial fills).

        Useful for: exact fill-price tracking, slippage measurement,
        adjusting stop quantities on partial TP fills.

        Key fields:
            event.client_order_id   — which order was filled
            event.order_side        — BUY or SELL
            event.last_qty          — fill quantity (Quantity)
            event.last_px           — fill price (Price)
            event.position_id       — associated position
            event.instrument_id     — instrument
        """
        # Optional: implement fill tracking, slippage logging, etc.
        pass

    # ===================================================================
    # POSITION EVENTS
    # ===================================================================

    def on_position_opened(self, event: PositionOpened) -> None:
        """Called when a new position is created (entry order filled).

        This is where you submit exit orders (stop-loss, take-profit)
        linked to the position via position_id.

        CRITICAL precision rules:
        - ALWAYS use self.instrument.make_price(value) for prices
        - ALWAYS use self.instrument.make_qty(value) for quantities
        - Wrong precision → OrderDenied by RiskEngine
        """
        position = self.cache.position(event.position_id)
        if position is None:
            return

        entry_price = position.avg_px_open
        qty = position.quantity
        is_long = position.side.name == "LONG"
        pid = event.position_id
        stop_side = OrderSide.SELL if is_long else OrderSide.BUY

        # --- Calculate exit levels (replace with your logic) ---
        # Example: fixed percentage stop & TP. For production use ATR, support/resistance, etc.
        stop_distance = entry_price * 0.02   # 2% stop
        tp_distance = entry_price * 0.04     # 4% take-profit

        if is_long:
            stop_px = entry_price - stop_distance
            tp_px = entry_price + tp_distance
        else:
            stop_px = entry_price + stop_distance
            tp_px = entry_price - tp_distance

        # IMPORTANT: make_price rounds to instrument's declared precision
        stop_price = self.instrument.make_price(stop_px)
        tp_price = self.instrument.make_price(tp_px)

        # Submit stop-loss (linked to this position)
        stop_order = self.order_factory.stop_market(
            instrument_id=self.instrument_id,
            order_side=stop_side,
            quantity=qty,
            trigger_price=stop_price,
            trigger_type=TriggerType.LAST_PRICE,  # NOT LAST_TRADE (doesn't exist)
            reduce_only=True,
        )
        self.submit_order(stop_order, position_id=pid)

        # Submit take-profit (linked to this position)
        tp_order = self.order_factory.limit(
            instrument_id=self.instrument_id,
            order_side=stop_side,
            quantity=qty,
            price=tp_price,
            reduce_only=True,
            post_only=True,  # Ensures maker fee tier
        )
        self.submit_order(tp_order, position_id=pid)

        # Track exit orders for cleanup on close
        self._open_positions[pid.value] = {{
            "stop_oid": stop_order.client_order_id,
            "tp_oid": tp_order.client_order_id,
            "entry_price": entry_price,
        }}

        self.log.info(
            f"Position opened: {{pid}} {{'LONG' if is_long else 'SHORT'}} "
            f"qty={{qty}} @ {{entry_price:.4f}}, SL={{stop_price}}, TP={{tp_price}}"
        )

    def on_position_changed(self, event: PositionChanged) -> None:
        """Called when position quantity/side changes (e.g. partial exit fill).

        In HEDGING mode with split TP orders (e.g. 60%/40%), a partial TP fill
        changes the position quantity. You may need to adjust the stop order
        quantity here to stay size-consistent.
        """
        # Optional: adjust stop quantity to match remaining position size
        # position = self.cache.position(event.position_id)
        # if position and position.quantity != original_qty:
        #     # modify stop order quantity...
        #     pass
        pass

    def on_position_closed(self, event: PositionClosed) -> None:
        """Called when a position is fully closed.

        Clean up tracking state. Cancel any remaining exit orders that
        didn't trigger (e.g. if stop filled, cancel TP and vice versa).
        """
        pid_str = event.position_id.value
        tracking = self._open_positions.pop(pid_str, None)

        if tracking:
            # Cancel remaining exit orders that are still open
            for key in ("stop_oid", "tp_oid"):
                oid = tracking.get(key)
                if oid:
                    order = self.cache.order(oid)
                    if order and not order.is_closed:
                        self.cancel_order(order)

        # Log PnL — use self.cache.position() since closed positions are retained
        position = self.cache.position(event.position_id)
        if position:
            self.log.info(
                f"Position closed: {{event.position_id}} "
                f"PnL={{position.realized_pnl}}"
            )

    # ===================================================================
    # SIGNAL & GENERIC EVENTS
    # ===================================================================

    def on_signal(self, signal) -> None:
        """Handle lightweight signals (int, float, str) from actors/strategies.

        Subscribe in on_start():  self.subscribe_signal("signal_name")
        Publish from any actor:   self.publish_signal(name="alert", value="high", ts_event=...)
        """
        pass

    def on_event(self, event) -> None:
        """Universal event fallback — catches ALL unhandled events.

        Useful for handling TimeEvent from clock timers:
            if isinstance(event, TimeEvent):
                if event.name == "rebalance":
                    self._rebalance()
        """
        pass

    # ===================================================================
    # RISK GUARD INTEGRATION
    # ===================================================================

    def _on_risk_guard_state(self, action: str) -> None:
        """Handle RiskGuard breach signals via msgbus.

        Published by RiskGuardActor on topic "risk.guard.state".
        Subscribed in on_start() via self.msgbus.subscribe().

        Actions:
            "reduce_only" — only allow position-reducing orders
            "halt_new"    — block all new orders entirely
            "flatten_all" — flatten all positions immediately
            "normal"      — breach cleared, resume normal trading
        """
        prev = self._risk_state
        self._risk_state = action
        self.log.warning(f"RiskGuard state: {{prev}} → {{action}}")

        if action == "flatten_all":
            self.close_all_positions(self.instrument_id)
        elif action == "normal" and prev != "normal":
            self.log.info("Risk limits cleared — normal trading resumed")

    # ===================================================================
    # ORDER HELPERS
    # ===================================================================

    def _submit_entry(self, side: OrderSide) -> None:
        """Submit a market entry order with risk checks.

        IMPORTANT:
        - Always use instrument.make_qty() for quantity precision
        - Quantity is UNSIGNED — never pass negative values
        - Check risk state before submitting
        """
        if self._risk_state in ("halt_new", "flatten_all"):
            return
        if self._risk_state == "reduce_only":
            return  # No new entries in reduce_only mode

        # Precision-safe quantity
        qty = self.instrument.make_qty(self.trade_size)

        order = self.order_factory.market(
            instrument_id=self.instrument_id,
            order_side=side,
            quantity=qty,
            # tags=["ENTRY"],  # Optional: arbitrary string tags for filtering
        )
        self.submit_order(order)

        # Alternative order types for reference:
        #
        # Limit order:
        # order = self.order_factory.limit(
        #     instrument_id=self.instrument_id,
        #     order_side=side,
        #     quantity=qty,
        #     price=self.instrument.make_price(target_price),
        #     time_in_force=TimeInForce.GTC,
        #     post_only=True,
        # )
        #
        # Stop-market order:
        # order = self.order_factory.stop_market(
        #     instrument_id=self.instrument_id,
        #     order_side=side,
        #     quantity=qty,
        #     trigger_price=self.instrument.make_price(trigger),
        #     trigger_type=TriggerType.LAST_PRICE,
        # )

    def _cleanup_order_tracking(self, client_order_id) -> None:
        """Remove a rejected/denied order from position tracking.

        Called by on_order_rejected and on_order_denied to prevent
        ghost entries in _open_positions.
        """
        for pid_str, tracking in list(self._open_positions.items()):
            for key in ("stop_oid", "tp_oid"):
                if tracking.get(key) == client_order_id:
                    tracking.pop(key, None)
'''

# ===========================================================================
# TICK_SCAFFOLD — Complete tick-based strategy template
# ===========================================================================

TICK_SCAFFOLD = '''"""
{name} — Tick-based trading strategy.

Generated by TinoHelm scaffold generator.
Production-level template with full event handling, order management,
position lifecycle, and risk integration.

Architecture notes (READ BEFORE EDITING):
- NautilusTrader uses HEDGING OMS mode: each entry = independent position.
- Config fields instrument_id, order_id_tag, manage_stop are injected by
  the portfolio loader — NEVER hardcode them.
- Do NOT access self.clock, self.log, self.cache in __init__().
- All subscribe_*() calls MUST happen in on_start().
- Always use instrument.make_price() / make_qty() for order precision.
- Quantity is UNSIGNED. TriggerType.LAST_TRADE does NOT exist.
"""
from __future__ import annotations

from decimal import Decimal
from typing import Any

from nautilus_trader.config import StrategyConfig
from nautilus_trader.model import InstrumentId
from nautilus_trader.model.data import QuoteTick, TradeTick
from nautilus_trader.model.enums import OrderSide, TriggerType
from nautilus_trader.model.events import (
    OrderDenied,
    OrderFilled,
    OrderRejected,
    PositionChanged,
    PositionClosed,
    PositionOpened,
)
from nautilus_trader.model.identifiers import PositionId
from nautilus_trader.model.objects import Price, Quantity
from nautilus_trader.trading.strategy import Strategy

from tinohelm.strategy.state import stateful
from tinohelm.strategy.utils import is_paused, setup_pause_support


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

class {class_name}Config(StrategyConfig):
    """Configuration for {class_name}.

    Fields injected by loader (do NOT set in params):
        instrument_id, order_id_tag, manage_stop
    """
    instrument_id: InstrumentId
    trade_size: Decimal = Decimal("0.01")
    # --- Add your custom params here ---


# ---------------------------------------------------------------------------
# Strategy
# ---------------------------------------------------------------------------

@stateful("tick_count")
class {class_name}(Strategy):
    """{name} tick-based trading strategy.

    HEDGING mode: each submit_order() creates an independent position.
    Link exit orders via: submit_order(order, position_id=pid)

    Tick data fields:
        QuoteTick: tick.bid_price, tick.ask_price, tick.bid_size, tick.ask_size
        TradeTick: tick.price, tick.size, tick.aggressor_side
    """

    def __init__(self, config: {class_name}Config) -> None:
        super().__init__(config)
        self.instrument_id = config.instrument_id
        self.trade_size = config.trade_size
        self.tick_count: int = 0
        self._open_positions: dict[str, dict] = {{}}
        self._risk_state: str = "normal"
        # WARNING: Do NOT access self.log/self.clock/self.cache here.

    # ===================================================================
    # LIFECYCLE
    # ===================================================================

    def on_start(self) -> None:
        """Subscribe to data and initialize."""
        self.instrument = self.cache.instrument(self.instrument_id)
        if self.instrument is None:
            self.log.error(f"Instrument not found: {{self.instrument_id}}")
            self.stop()
            return

        self._venue = self.instrument.venue
        self._currency = self.instrument.quote_currency

        setup_pause_support(self)

        # Subscribe to tick data — REQUIRED for callbacks to fire
        self.subscribe_quote_ticks(self.instrument_id)
        # self.subscribe_trade_ticks(self.instrument_id)  # Uncomment if needed

        # RiskGuard integration
        self.msgbus.subscribe("risk.guard.state", self._on_risk_guard_state)

        self.log.info(f"Strategy started on {{self.instrument_id}}")

    def on_stop(self) -> None:
        """Clean up on stop. manage_stop=True auto-runs market_exit() first."""
        self.cancel_all_orders(self.instrument_id)
        self.close_all_positions(self.instrument_id)
        self.log.info("Strategy stopped")

    # ===================================================================
    # DATA EVENTS
    # ===================================================================

    def on_quote_tick(self, tick: QuoteTick) -> None:
        """Called on each quote tick update.

        Fields: tick.bid_price, tick.ask_price, tick.bid_size, tick.ask_size
        """
        if is_paused(self):
            return
        if self._risk_state == "halt_new":
            return

        self.tick_count += 1
        # --- YOUR TRADING LOGIC HERE ---
        pass

    def on_trade_tick(self, tick: TradeTick) -> None:
        """Called on each trade tick.

        Fields: tick.price, tick.size, tick.aggressor_side
        """
        pass

    # ===================================================================
    # ORDER EVENTS
    # ===================================================================

    def on_order_rejected(self, event: OrderRejected) -> None:
        """Exchange rejected order. Clean up tracking state."""
        self.log.warning(f"Order REJECTED: {{event.client_order_id}} — {{event.reason}}")
        self._cleanup_order_tracking(event.client_order_id)

    def on_order_denied(self, event: OrderDenied) -> None:
        """NT RiskEngine denied order. Use make_price/make_qty to avoid."""
        self.log.warning(f"Order DENIED: {{event.client_order_id}} — {{event.reason}}")
        self._cleanup_order_tracking(event.client_order_id)

    def on_order_filled(self, event: OrderFilled) -> None:
        """Optional: track fills, measure slippage, adjust stop qty on partial TP."""
        pass

    # ===================================================================
    # POSITION EVENTS
    # ===================================================================

    def on_position_opened(self, event: PositionOpened) -> None:
        """Submit exit orders (stop-loss, take-profit) linked to the position.

        Always use instrument.make_price() / make_qty() for precision safety.
        """
        position = self.cache.position(event.position_id)
        if position is None:
            return

        entry_price = position.avg_px_open
        qty = position.quantity
        is_long = position.side.name == "LONG"
        pid = event.position_id
        stop_side = OrderSide.SELL if is_long else OrderSide.BUY

        # Replace with your exit level logic (ATR-based, volatility, etc.)
        sl = entry_price * (0.98 if is_long else 1.02)
        tp = entry_price * (1.04 if is_long else 0.96)

        stop_order = self.order_factory.stop_market(
            instrument_id=self.instrument_id,
            order_side=stop_side,
            quantity=qty,
            trigger_price=self.instrument.make_price(sl),
            trigger_type=TriggerType.LAST_PRICE,
            reduce_only=True,
        )
        self.submit_order(stop_order, position_id=pid)

        tp_order = self.order_factory.limit(
            instrument_id=self.instrument_id,
            order_side=stop_side,
            quantity=qty,
            price=self.instrument.make_price(tp),
            reduce_only=True,
            post_only=True,
        )
        self.submit_order(tp_order, position_id=pid)

        self._open_positions[pid.value] = {{
            "stop_oid": stop_order.client_order_id,
            "tp_oid": tp_order.client_order_id,
        }}
        self.log.info(f"Position opened: {{pid}} @ {{entry_price:.4f}}")

    def on_position_changed(self, event: PositionChanged) -> None:
        """Optional: adjust stop qty after partial TP fill."""
        pass

    def on_position_closed(self, event: PositionClosed) -> None:
        """Clean up tracking and cancel remaining exit orders."""
        tracking = self._open_positions.pop(event.position_id.value, None)
        if tracking:
            for key in ("stop_oid", "tp_oid"):
                oid = tracking.get(key)
                if oid:
                    order = self.cache.order(oid)
                    if order and not order.is_closed:
                        self.cancel_order(order)

        position = self.cache.position(event.position_id)
        if position:
            self.log.info(f"Position closed: {{event.position_id}} PnL={{position.realized_pnl}}")

    # ===================================================================
    # SIGNAL & GENERIC EVENTS
    # ===================================================================

    def on_signal(self, signal) -> None:
        """Handle signals from actors. Subscribe via self.subscribe_signal(name)."""
        pass

    def on_event(self, event) -> None:
        """Catch-all: TimeEvent from timers, or any unhandled event."""
        pass

    # ===================================================================
    # RISK GUARD & HELPERS
    # ===================================================================

    def _on_risk_guard_state(self, action: str) -> None:
        """Handle RiskGuard breach: reduce_only / halt_new / flatten_all / normal."""
        prev = self._risk_state
        self._risk_state = action
        self.log.warning(f"RiskGuard: {{prev}} → {{action}}")
        if action == "flatten_all":
            self.close_all_positions(self.instrument_id)

    def _submit_entry(self, side: OrderSide) -> None:
        """Submit market entry with risk checks and precision-safe quantity."""
        if self._risk_state in ("halt_new", "flatten_all", "reduce_only"):
            return
        order = self.order_factory.market(
            instrument_id=self.instrument_id,
            order_side=side,
            quantity=self.instrument.make_qty(self.trade_size),
        )
        self.submit_order(order)

    def _cleanup_order_tracking(self, client_order_id) -> None:
        """Remove rejected/denied order from position tracking."""
        for tracking in self._open_positions.values():
            for key in ("stop_oid", "tp_oid"):
                if tracking.get(key) == client_order_id:
                    tracking.pop(key, None)
'''

# ===========================================================================
# PORTFOLIO_YAML_SCAFFOLD — Portfolio configuration template
# ===========================================================================

PORTFOLIO_YAML_SCAFFOLD = '''# {name} — Portfolio Configuration
#
# This file defines a multi-symbol portfolio. The loader creates one strategy
# instance per symbol, each with its own instrument_id, bar_type, and order_id_tag.
#
# Required fields: strategy.class, symbols, interval
# All other fields are optional with sensible defaults.

# ---------------------------------------------------------------------------
# Strategy class reference
# ---------------------------------------------------------------------------
strategy:
  class: "strategy:{class_name}"          # module:ClassName — "strategy" = strategy.py in this folder
  # config: "strategy:{class_name}Config" # Optional — defaults to class name + "Config"

# ---------------------------------------------------------------------------
# Symbols to trade (one strategy instance per symbol)
# ---------------------------------------------------------------------------
# Format: SYMBOL-TYPE (e.g., BTCUSDT-PERP, ETHUSDT-SPOT)
# Do NOT append .BINANCE — the loader does this automatically.
symbols:
  - BTCUSDT-PERP
  # - ETHUSDT-PERP
  # - SOLUSDT-PERP

# ---------------------------------------------------------------------------
# Bar interval
# ---------------------------------------------------------------------------
# Supported: 1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d
# Only 1m data needs to be stored — higher intervals are auto-aggregated.
interval: 5m

# ---------------------------------------------------------------------------
# Strategy parameters (passed to StrategyConfig constructor per symbol)
# ---------------------------------------------------------------------------
# Do NOT set here: instrument_id, bar_type, order_id_tag, manage_stop
# (these are injected by the loader automatically)
params:
  trade_size: 0.01
  # lookback_window: 100
  # stop_atr_mult: 1.5

# ---------------------------------------------------------------------------
# Account settings (for backtesting)
# ---------------------------------------------------------------------------
account:
  starting_balance: 10000
  currency: USDT
  leverage: 10

# ---------------------------------------------------------------------------
# Risk Guard (optional — creates RiskGuardActor automatically)
# ---------------------------------------------------------------------------
# Publishes breach actions via msgbus topic "risk.guard.state".
# Strategies subscribe in on_start() to react to: reduce_only, halt_new, flatten_all.
risk_guard:
  enabled: true
  check_interval_secs: 10
  daily_stop_loss_pct: -0.02       # Daily stop loss threshold
  max_drawdown_pct: -0.10          # Max drawdown from peak equity
  max_total_exposure: 50000        # Max total position notional value
  max_positions: 5                 # Max concurrent open positions
  breach_action: reduce_only       # "reduce_only" or "halt_new"

# ---------------------------------------------------------------------------
# Custom actors (optional — additional actors beyond risk_guard)
# ---------------------------------------------------------------------------
# actors:
#   - name: risk_guard              # Loads from ~/.tino/actors/ or built-in
#     params:
#       daily_stop_loss_pct: -0.02
#   - class: "./my_monitor:MonitorActor"  # Relative path inside this folder
#     params: {{}}

# ---------------------------------------------------------------------------
# Optuna optimization ranges (optional — for parameter sweep)
# ---------------------------------------------------------------------------
# optimize:
#   trade_size:
#     type: float
#     min: 0.001
#     max: 0.1
#     step: 0.001
#   lookback_window:
#     type: int
#     min: 20
#     max: 200
#     step: 10
'''


# ===========================================================================
# Generator functions
# ===========================================================================

def generate_scaffold(
    name: str,
    strategies_dir: str | Path,
    scaffold_type: str = "bar",
) -> Path:
    """Generate a strategy scaffold file.

    Args:
        name: Strategy name (snake_case, valid Python identifier)
        strategies_dir: Directory to write the file
        scaffold_type: "bar" or "tick"

    Returns:
        Path to the generated file
    """
    if not re.match(r'^[a-zA-Z_][a-zA-Z0-9_]*$', name):
        raise ValueError(f"Invalid strategy name: must be a valid Python identifier, got '{name}'")

    strategies_dir = Path(strategies_dir)
    strategies_dir.mkdir(parents=True, exist_ok=True)

    class_name = "".join(word.capitalize() for word in name.split("_"))

    template = BAR_SCAFFOLD if scaffold_type == "bar" else TICK_SCAFFOLD
    content = template.format(name=name, class_name=class_name)

    file_path = (strategies_dir / f"{name}.py").resolve()
    if not str(file_path).startswith(str(strategies_dir.resolve())):
        raise ValueError("Path traversal detected in strategy name")
    if file_path.exists():
        raise FileExistsError(f"Strategy file already exists: {file_path}")

    file_path.write_text(content)
    logger.info(f"Generated {scaffold_type} scaffold: {file_path}")
    return file_path


def generate_portfolio_scaffold(
    name: str,
    strategies_dir: str | Path,
    strategy_type: str = "bar",
) -> Path:
    """Generate a portfolio scaffold folder with strategy.py + portfolio.yaml.

    Creates::

        {strategies_dir}/{name}/
        ├── portfolio.yaml   # Portfolio configuration
        └── strategy.py      # Strategy template (bar or tick based)

    Args:
        name: Portfolio name (snake_case, valid Python identifier)
        strategies_dir: Parent directory for the portfolio folder
        strategy_type: "bar" or "tick" — determines the strategy template

    Returns:
        Path to the generated portfolio folder
    """
    if not re.match(r'^[a-zA-Z_][a-zA-Z0-9_]*$', name):
        raise ValueError(
            f"Invalid portfolio name: must be a valid Python identifier, got '{name}'"
        )

    strategies_dir = Path(strategies_dir)
    portfolio_dir = (strategies_dir / name).resolve()

    if not str(portfolio_dir).startswith(str(strategies_dir.resolve())):
        raise ValueError("Path traversal detected in portfolio name")
    if portfolio_dir.exists():
        raise FileExistsError(f"Portfolio folder already exists: {portfolio_dir}")

    portfolio_dir.mkdir(parents=True)

    class_name = "".join(word.capitalize() for word in name.split("_"))

    # Write strategy.py (using the selected scaffold type)
    scaffold = TICK_SCAFFOLD if strategy_type == "tick" else BAR_SCAFFOLD
    strategy_content = scaffold.format(name=name, class_name=class_name)
    (portfolio_dir / "strategy.py").write_text(strategy_content)

    # Write portfolio.yaml
    yaml_content = PORTFOLIO_YAML_SCAFFOLD.format(name=name, class_name=class_name)
    (portfolio_dir / "portfolio.yaml").write_text(yaml_content)

    logger.info(f"Generated portfolio scaffold: {portfolio_dir}")
    return portfolio_dir
