"""Strategy scaffold generator."""
from __future__ import annotations

import logging
import re
from pathlib import Path

logger = logging.getLogger(__name__)

BAR_SCAFFOLD = '''"""
{name} — Bar-based trading strategy.

Generated by TinoHelm scaffold generator.
Customize the on_bar() method with your trading logic.
"""
from __future__ import annotations

from decimal import Decimal

from nautilus_trader.config import StrategyConfig
from nautilus_trader.model import InstrumentId
from nautilus_trader.model.data import Bar, BarType
from nautilus_trader.model.enums import OrderSide
from nautilus_trader.model.identifiers import InstrumentId
from nautilus_trader.model.objects import Quantity
from nautilus_trader.trading.strategy import Strategy


class {class_name}Config(StrategyConfig):
    """Configuration for {class_name}.

    Attributes:
        instrument_id: The instrument to trade (e.g. "BTCUSDT-PERP.BINANCE").
        bar_type: The bar type to subscribe to (e.g. "BTCUSDT-PERP.BINANCE-1-HOUR-LAST-INTERNAL").
        trade_size: Order quantity per trade.
    """
    instrument_id: InstrumentId
    bar_type: BarType
    trade_size: Decimal = Decimal("0.01")


class {class_name}(Strategy):
    """{name} trading strategy.

    Lifecycle hooks available (implement as needed):
        on_start()            — Subscribe to data, initialize indicators
        on_stop()             — Cancel orders, close positions, cleanup
        on_bar(bar)           — Core trading logic on each new bar
        on_quote_tick(tick)   — Handle quote tick updates
        on_trade_tick(tick)   — Handle trade tick updates
        on_order_filled(event) — React to order fills
        on_position_opened(event)  — React to new positions
        on_position_changed(event) — React to position updates
        on_position_closed(event)  — React to position closures
        on_event(event)       — Catch-all event handler

    Useful APIs:
        self.order_factory.market(instrument_id, side, quantity)
        self.order_factory.limit(instrument_id, side, quantity, price)
        self.submit_order(order)
        self.cancel_order(order)
        self.cancel_all_orders(instrument_id)
        self.close_all_positions(instrument_id)
        self.cache.instrument(instrument_id)
        self.cache.positions(instrument_id=...)
        self.portfolio.net_exposures(venue)
        self.register_indicator_for_bars(bar_type, indicator)
    """

    def __init__(self, config: {class_name}Config) -> None:
        super().__init__(config)
        self.instrument_id = config.instrument_id
        self.bar_type = config.bar_type
        self.trade_size = config.trade_size
        # Initialize your state variables here
        # NOTE: Do NOT call self.log or self.clock here (not yet registered)

    def on_start(self) -> None:
        """Called when the strategy starts. Subscribe to data here."""
        self.instrument = self.cache.instrument(self.instrument_id)
        if self.instrument is None:
            self.log.error(f"Instrument not found: {{self.instrument_id}}")
            self.stop()
            return

        # Subscribe to bar data
        self.subscribe_bars(self.bar_type)

        # Optional: register indicators
        # self.register_indicator_for_bars(self.bar_type, my_indicator)

        self.log.info(f"Strategy started on {{self.instrument_id}}")

    def on_bar(self, bar: Bar) -> None:
        """Called on each new bar. Implement your trading logic here."""
        # Example: Access bar data
        # open_price = bar.open
        # high = bar.high
        # low = bar.low
        # close = bar.close
        # volume = bar.volume

        # TODO: Implement your trading logic
        pass

    def on_stop(self) -> None:
        """Called when the strategy stops. Clean up here."""
        self.cancel_all_orders(self.instrument_id)
        self.close_all_positions(self.instrument_id)
        self.log.info("Strategy stopped")
'''

TICK_SCAFFOLD = '''"""
{name} — Tick-based trading strategy.

Generated by TinoHelm scaffold generator.
Customize the on_quote_tick() or on_trade_tick() method with your trading logic.
"""
from __future__ import annotations

from decimal import Decimal

from nautilus_trader.config import StrategyConfig
from nautilus_trader.model import InstrumentId
from nautilus_trader.model.data import QuoteTick, TradeTick
from nautilus_trader.model.enums import OrderSide
from nautilus_trader.model.objects import Quantity
from nautilus_trader.trading.strategy import Strategy


class {class_name}Config(StrategyConfig):
    """Configuration for {class_name}."""
    instrument_id: InstrumentId
    trade_size: Decimal = Decimal("0.01")


class {class_name}(Strategy):
    """{name} tick-based trading strategy."""

    def __init__(self, config: {class_name}Config) -> None:
        super().__init__(config)
        self.instrument_id = config.instrument_id
        self.trade_size = config.trade_size

    def on_start(self) -> None:
        self.instrument = self.cache.instrument(self.instrument_id)
        if self.instrument is None:
            self.log.error(f"Instrument not found: {{self.instrument_id}}")
            self.stop()
            return
        self.subscribe_quote_ticks(self.instrument_id)
        # self.subscribe_trade_ticks(self.instrument_id)
        self.log.info(f"Strategy started on {{self.instrument_id}}")

    def on_quote_tick(self, tick: QuoteTick) -> None:
        """Called on each quote tick. Implement your trading logic here."""
        # tick.bid_price, tick.ask_price, tick.bid_size, tick.ask_size
        pass

    def on_trade_tick(self, tick: TradeTick) -> None:
        """Called on each trade tick."""
        # tick.price, tick.size, tick.aggressor_side
        pass

    def on_stop(self) -> None:
        self.cancel_all_orders(self.instrument_id)
        self.close_all_positions(self.instrument_id)
        self.log.info("Strategy stopped")
'''


def generate_scaffold(
    name: str,
    strategies_dir: str | Path,
    scaffold_type: str = "bar",
) -> Path:
    """Generate a strategy scaffold file.

    Args:
        name: Strategy name (snake_case)
        strategies_dir: Directory to write the file
        scaffold_type: "bar", "tick", or "book"

    Returns:
        Path to the generated file
    """
    if not re.match(r'^[a-zA-Z_][a-zA-Z0-9_]*$', name):
        raise ValueError(f"Invalid strategy name: must be a valid Python identifier, got '{name}'")

    strategies_dir = Path(strategies_dir)
    strategies_dir.mkdir(parents=True, exist_ok=True)

    # Convert name to class name
    class_name = "".join(word.capitalize() for word in name.split("_"))

    template = BAR_SCAFFOLD if scaffold_type == "bar" else TICK_SCAFFOLD

    content = template.format(name=name, class_name=class_name)

    file_path = (strategies_dir / f"{name}.py").resolve()
    if not str(file_path).startswith(str(strategies_dir.resolve())):
        raise ValueError("Path traversal detected in strategy name")
    if file_path.exists():
        raise FileExistsError(f"Strategy file already exists: {file_path}")

    file_path.write_text(content)
    logger.info(f"Generated {scaffold_type} scaffold: {file_path}")
    return file_path
